export const TYPES = {
  SET_NAVIGATION_STATE: 'SET_NAVIGATION_STATE',
  SET_CURRENT_ROUTE_NAME: 'SET_CURRENT_ROUTE_NAME',
  THEME: {
    CHANGE_THEME: 'CHANGE_THEME',
    SET_DEFAULT_THEME: 'SET_DEFAULT_THEME',
  },
  PHOTOS: {
    GET_LIST_PHOTOS_START: 'GET_LIST_PHOTOS_START',
    GET_LIST_PHOTOS_FAILED: 'GET_LIST_PHOTOS_FAILED',
    GET_LIST_PHOTOS_SUCCESS: 'GET_LIST_PHOTOS_SUCCESS',
  },
};
